name: Feature request
description: 機能要望
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 背景 / 課題
      description: どんな困りごとを解決したいかを記載してください。
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: 期待する振る舞いを具体的に記載してください。
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した他の方法があれば記載してください。

  - type: dropdown
    id: scope
    attributes:
      label: 対象
      options:
        - GUI
        - CLI
        - Build / Release
        - Docs
        - Other
